#!/usr/bin/env bash
# image-scripts-test.sh - plain-bash tests of verify-image.sh and check-pins.sh; no container engine, no network.
#
# Usage: image-scripts-test.sh [-h|--help]
#
# verify-image.sh runs against a stubbed `docker` that executes the in-image commands on the host, with a
# throwaway CA (root + intermediate) generated by openssl and a stub keytool for the JVM cases;
# check-pins.sh runs against temporary files. The scripts under test are looked up in $SCRIPTS_DIR, next
# to this file, or in ../ci/ (the layout scripts/ci/*.sh + scripts/test/*-test.sh).
# Needs: bash, openssl, awk, sed, grep, tr, mktemp, sort.
#
# Exit codes: 0 every test passed; 1 at least one test failed; 2 usage error or missing prerequisite.
set -euo pipefail

usage() { sed -n '2,/^set -euo pipefail$/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; }
case ${1:-} in
  -h | --help) usage; exit 0 ;;
  "") ;;
  *) echo "image-scripts-test.sh: unknown argument $1" >&2; exit 2 ;;
esac

here=$(cd "$(dirname "$0")" && pwd)
scripts=""
for d in ${SCRIPTS_DIR:+"$SCRIPTS_DIR"} "$here" "$here/../ci"; do
  if [[ -x $d/verify-image.sh && -x $d/check-pins.sh ]]; then scripts=$(cd "$d" && pwd); break; fi
done
[[ -n $scripts ]] || { echo "image-scripts-test.sh: verify-image.sh and check-pins.sh not found (set SCRIPTS_DIR)" >&2; exit 2; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/bin" "$work/tools" "$work/jvm" "$work/javaonly" "$work/keys"

# A minimal PATH: the host's own java/keytool must not leak into the "no JVM" cases.
for tool in bash sh env awk openssl grep sed tr mktemp rm head tail cat sort; do
  path=$(command -v "$tool") || { echo "image-scripts-test.sh: $tool is required" >&2; exit 2; }
  ln -s "$path" "$work/bin/$tool"
done

# Stub docker: `image inspect` (USER from $STUB_USER; images named missing/* do not exist),
# `run --rm --entrypoint E [-e K=V]... IMAGE ARGS...` runs E ARGS on the host, and the CLI version commands.
cat >"$work/tools/docker" <<'EOF'
#!/usr/bin/env bash
case $1 in
  image)
    [[ ${!#} == missing/* ]] && { echo "Error: No such image: ${!#}" >&2; exit 1; }
    if [[ $* == *--format* ]]; then echo "${STUB_USER-1001:1001}"; fi ;;
  run)
    shift; envs=(); entry=""
    while [[ $# -gt 0 ]]; do
      case $1 in --rm) shift ;; --entrypoint) entry=$2; shift 2 ;; -e) envs+=("$2"); shift 2 ;; *) break ;; esac
    done
    shift
    exec env ${envs[@]+"${envs[@]}"} "$entry" "$@" ;;
  --version) echo "Docker version 0.0.0-stub" ;;
  compose | buildx) echo "$1 stub" ;;
  *) echo "stub docker: unexpected $*" >&2; exit 64 ;;
esac
EOF
for tool in git jq helm kubectl kind hadolint shellcheck yq crane; do
  printf '#!/bin/sh\necho "%s stub"\n' "$tool" >"$work/tools/$tool"
done
printf '#!/bin/sh\nprintf "HTTP 200"\n' >"$work/tools/curl"
# shellcheck disable=SC2016 # $KEYTOOL_LIST is expanded by the stub when it runs
printf '#!/bin/sh\ncat "$KEYTOOL_LIST"\n' >"$work/jvm/keytool"
printf '#!/bin/sh\necho "openjdk stub"\n' | tee "$work/jvm/java" >"$work/javaonly/java"
chmod +x "$work"/tools/* "$work"/jvm/* "$work"/javaonly/*

# A throwaway CA: root + intermediate; the OS store = the bundle (as update-ca-certificates would add it).
ossl() { openssl "$@" >/dev/null 2>&1; }
ossl req -x509 -newkey rsa:2048 -nodes -sha256 -days 2 -subj "/CN=Test Root" -keyout "$work/keys/root.key" -out "$work/root.pem" \
  -addext "basicConstraints=critical,CA:TRUE" -addext "keyUsage=critical,keyCertSign,cRLSign"
ossl req -newkey rsa:2048 -nodes -subj "/CN=Test Intermediate" -keyout "$work/keys/int.key" -out "$work/keys/int.csr"
printf 'basicConstraints=critical,CA:TRUE\nkeyUsage=critical,keyCertSign,cRLSign\n' >"$work/keys/ext"
ossl x509 -req -in "$work/keys/int.csr" -CA "$work/root.pem" -CAkey "$work/keys/root.key" -CAcreateserial -days 2 -sha256 \
  -extfile "$work/keys/ext" -out "$work/int.pem"
ossl req -x509 -newkey rsa:2048 -nodes -sha256 -days 2 -subj "/CN=Unrelated Root" -keyout "$work/keys/other.key" -out "$work/other.pem"
cat "$work/root.pem" "$work/int.pem" >"$work/bundle.pem"
cp "$work/bundle.pem" "$work/store.pem"
cat "$work/root.pem" "$work/keys/root.key" >"$work/bundle-with-key.pem"
listing() { for c in "$@"; do echo "Certificate fingerprint (SHA-256): $(openssl x509 -noout -fingerprint -sha256 -in "$c" | sed 's/^.*=//')"; done; }
listing "$work/root.pem" "$work/int.pem" >"$work/cacerts-full.txt"
listing "$work/root.pem" >"$work/cacerts-root-only.txt"

failures=0
# expect <name> <exit status> <pattern in the output, or ''> <PATH> <command...>
expect() {
  local name=$1 want=$2 pattern=$3 path=$4 out status
  shift 4
  set +e
  out=$(env -i HOME="$work" PATH="$path" STUB_USER="${STUB_USER-1001:1001}" KEYTOOL_LIST="${KEYTOOL_LIST:-}" \
    CONTAINER_ENGINE="${CONTAINER_ENGINE:-docker}" "$@" 2>&1)
  status=$?
  set -e
  if [[ $status -eq $want && ( -z $pattern || $out == *"$pattern"* ) ]]; then
    echo "ok    $name"
  else
    echo "FAIL  $name: exit $status (want $want), expected output: ${pattern:-anything}"
    while IFS= read -r line; do echo "      | $line"; done <<<"$out"
    failures=$((failures + 1))
  fi
}

plain="$work/tools:$work/bin"
jvm="$work/tools:$work/jvm:$work/bin"
javaonly="$work/tools:$work/javaonly:$work/bin"
verify=("$work/bin/bash" "$scripts/verify-image.sh")
ca=(--ca-bundle "$work/bundle.pem" --os-store "$work/store.pem")

expect "verify: --help" 0 "Usage: verify-image.sh" "$plain" "${verify[@]}" --help
expect "verify: runtime image without a JVM" 0 "2 certificate(s) in the OS store (no JVM)" "$plain" \
  "${verify[@]}" "${ca[@]}" --tls-url https://example.internal --summary "$work/summary.md" acme/runtime-base:dev
if grep -q '^| CA bundle in the trust stores | ok |' "$work/summary.md"; then echo "ok    verify: Markdown summary written"; else
  echo "FAIL  verify: Markdown summary"; failures=$((failures + 1)); fi
KEYTOOL_LIST="$work/cacerts-full.txt" expect "verify: JVM cacerts holds every certificate" 0 "and the JVM cacerts" "$jvm" \
  "${verify[@]}" "${ca[@]}" acme/runtime-base:dev
KEYTOOL_LIST="$work/cacerts-root-only.txt" expect "verify: JVM cacerts lacks the intermediate" 1 "JVM cacerts lacks" "$jvm" \
  "${verify[@]}" "${ca[@]}" acme/runtime-base:dev
expect "verify: java without keytool" 1 "java without keytool" "$javaonly" "${verify[@]}" "${ca[@]}" acme/runtime-base:dev
expect "verify: OS store without the CA" 1 "OS store does not trust" "$plain" \
  "${verify[@]}" --ca-bundle "$work/bundle.pem" --os-store "$work/other.pem" acme/runtime-base:dev
expect "verify: private key in the bundle" 1 "contains a private key" "$plain" \
  "${verify[@]}" --ca-bundle "$work/bundle-with-key.pem" --os-store "$work/store.pem" acme/runtime-base:dev
expect "verify: ci-build with every tool, UID 1001" 0 "passed every check" "$plain" \
  "${verify[@]}" --kind ci-build --expect-uid 1001 "${ca[@]}" acme/ci-build:dev
expect "verify: failing --check" 1 "exit status 1, no output" "$plain" \
  "${verify[@]}" --no-ca --check 'test -d /nonexistent' acme/ci-build:dev
STUB_USER=root expect "verify: USER root" 1 "USER is 'root'" "$plain" "${verify[@]}" --no-ca acme/x:dev
STUB_USER=1000:1000 expect "verify: wrong UID" 1 "USER is '1000:1000'" "$plain" "${verify[@]}" --no-ca --expect-uid 1001 acme/x:dev
expect "verify: image missing" 3 "not present locally" "$plain" "${verify[@]}" missing/image:dev
CONTAINER_ENGINE=podman expect "verify: engine missing" 3 "'podman' not found" "$plain" "${verify[@]}" acme/x:dev
expect "verify: no image" 2 "no image given" "$plain" "${verify[@]}"
expect "verify: bad --kind" 2 "--kind must be" "$plain" "${verify[@]}" --kind other acme/x:dev

pins=("$work/bin/bash" "$scripts/check-pins.sh")
printf '# renovate: datasource=github-releases depName=helm/helm\nARG HELM_VERSION=v4.3.0\nARG KIND_VERSION="v0.33.0"\nFROM x\n' >"$work/Dockerfile"
printf '# pins\nHELM_VERSION=v4.3.0\nKIND_VERSION=v0.33.0\nOTHER=1\n' >"$work/same.env"
printf 'HELM_VERSION=v4.4.0\nKIND_VERSION=v0.33.0\n' >"$work/drift.env"
printf 'UNRELATED=1\n' >"$work/unrelated.env"
expect "pins: --help" 0 "Usage: check-pins.sh" "$plain" "${pins[@]}" --help
expect "pins: equal (quotes dropped)" 0 "ok       KIND_VERSION=v0.33.0" "$plain" "${pins[@]}" "$work/Dockerfile" "$work/same.env"
expect "pins: drift" 1 "DIFFERS  HELM_VERSION" "$plain" "${pins[@]}" "$work/Dockerfile" "$work/drift.env"
expect "pins: named key missing" 1 "MISSING  OTHER" "$plain" "${pins[@]}" "$work/Dockerfile" "$work/same.env" OTHER
expect "pins: nothing in common" 2 "no key is defined in both" "$plain" "${pins[@]}" "$work/Dockerfile" "$work/unrelated.env"
expect "pins: one argument" 2 "need a Dockerfile" "$plain" "${pins[@]}" "$work/Dockerfile"

if [[ $failures -ne 0 ]]; then
  echo "image-scripts-test.sh: $failures test(s) failed" >&2
  exit 1
fi
echo "image-scripts-test.sh: all tests passed"
